on:
  workflow_call:
    inputs:
      nome:
        required: true
        type: string

jobs:
  templ-test:     
    name: templ
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Teste
      run: echo ${{ inputs.nome }}

